name: Fetch API Data

on:
  workflow_dispatch:

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch API and save to dist/
        run: |
          mkdir -p dist
          curl --sL "https://script.google.com/macros/s/AKfycbyzktiAGRbMsTm885FIgnTg4EuUr6MxMQ5B9mVWzkRPZw-CbdNuzPEQ8boxkeRRA02t/exec" -o dist/rundown.json
          echo "API data fetched successfully!"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/
          cname: "mgp-2026.henrywu.tw"
          keep_files: true
